name: Docker Compose Actions Workflow
on: push
jobs:
  DockerCompose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm install
      - name: Create env file
        run: |
          touch .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "URL=${{ secrets.URL }}" >> .env
          echo "USER=${{ secrets.USER }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "USERADMIN=${{ secrets.USERADMIN }}" >> .env
          echo "PASSWORDADMIN=${{ secrets.PASSWORDADMIN }}" >> .env
          echo "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
      - name: Build the stack
        run: docker-compose up -d --force-recreate
      - name: "Test API"
        uses: indiesdev/curl@v1.1
        with:
          url: https://pharmacy.jmcv.codes/health
          method: "POST"
          accept: 200,201,204
          timeout: 2000
          log-response: false
          retries: 3
